<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<OutputType>Library</OutputType>
		
		<Title>Nt.Automaton</Title>
		<RootNamespace>Nt.Automaton</RootNamespace>
		<Description>Utility library for automaton operations</Description>
		<Version>1.2.3</Version>
	  
		<RepositoryUrl>https://github.com/Natvs/Nt.Automaton</RepositoryUrl>
		<RepositoryType>git</RepositoryType>

		<PackageId>Nt.Automaton</PackageId>
		<PackageVersion>1.2.3</PackageVersion>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageTags>automate ; automaton ; states</PackageTags>
		<PackageReleaseNotes>Review order of execution for actions in the StackAutomaton</PackageReleaseNotes>

		<AnalysisLevel>latest</AnalysisLevel>
		<AnalysisMode>Recommended</AnalysisMode>
		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
	</PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md">
	  <Visible>false</Visible>
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
	<None Include="..\Doc\**">
	  <Visible>false</Visible>
	  <Link>Doc\%(RecursiveDir)%(Filename)%(Extension)</Link>
	  <Pack>True</Pack>
	  <PackagePath>\Doc\</PackagePath>
	</None>
  </ItemGroup>

</Project>
