<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	  
		<Title>Nt.Automaton</Title>
		<RootNamespace>Nt.Automaton</RootNamespace>
		<Description>Automaton with states that can trigger actions</Description>
		<Version>1.1.1</Version>
	  
		<RepositoryUrl>https://github.com/Natvs/Nt.Automaton</RepositoryUrl>
		<RepositoryType>git</RepositoryType>

		<PackageId>Nt.Automaton</PackageId>
		<PackageVersion>1.1.1</PackageVersion>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageTags>automate ; automaton ; states</PackageTags>
		<PackageReleaseNotes>Minor patch to package 1.1.0</PackageReleaseNotes>
	</PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
